export interface GhosttyCorrelation {
  terminalId: string
  correlatedAt: number
}

export interface TrackedSession {
  id: string
  directory: string
  originalTitle: string
  /** Last title generated by this plugin. Used to decide whether we should
   * try another rename (we skip if OpenCode's current title already matches). */
  generatedTitle: string | null
  description: string
  /** Most recent user message id we've kicked a rename for, to avoid re-renaming
   * on trailing message.updated re-emits. */
  lastRenamedUserMessageID: string | null
  ghostty: GhosttyCorrelation | null
  times: {
    created: number
    updated: number
  }
}

export interface StateFile {
  version: 2
  updatedAt: number
  sessions: Record<string, TrackedSession>
}

export const STATE_VERSION = 2 as const
